
project:
  type: website

website:
  favicon: "images/favicon_blueearth.png"
  title: "About me"
  navbar:
    title: "About me"
    left:
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd

  page-footer:
    center: "© 2025 E. Neveu  Powered by Quarto with lux theme. Hosted by GitHub Pages"

format:
  html:
    theme: 
      - lux
      - styles.scss
    smooth-scroll: true
    toc: true
    
editor: visual




