
project:
  type: website

website:
  favicon: "images/favicon_blueearth.png"
  title: "About me"
  navbar:
    title: "About me"
    left:
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Maths for the Earth
        href: maths-for-the-earth.qmd
      - text: Rivers
        href: gallery/index.qmd
  page-footer:
    center: "© 2025 E. Neveu  Powered by Quarto with lux theme."

format:
  html:
    theme: 
      - lux
      - styles.scss
    smooth-scroll: true
    toc: true
    
editor: visual




