---
title: "Teaching"
---

In the School of Engineering, I am involved in three BsC : Energy & Environment Engineering, **Computer science and communication systems** and Life Sciences Engineering.

Teaching with small classes enables enhanced interactivity and project-based learning, allowing students to go from theory to practice.

-   Energy & Environment Engineering :

    -   *Traitement et gestion des données BsC1 4ECTS* : Basics of manipulations and graphics in Excel and Python, SqL, TimeSerie Database, Raspberry and connected sensors, Grafana

    -   *Traitement et gestion des données BsC2 2ECTS * : Statistical bases, correlation and regression, ANOVA and classification, learning principles and neural networks, well-posed problems and overfitting, time series: analysis and prediction. Python, scikit learn

    -   *Optimisation des aménagements hydroélectriques BsC 3 2ECTS* : under development

-   Computer Science and communication systems :

    -   *Algorithmics BsC 2 1st part 2ECTS* : complexity, dichotomy, sorting algorithms, introduction to profiling (measuring time execution), backtracking, branch & bound

    -   *Optimization for Machine Learning Bsc 3 1.2 ECTS* : learning principles, well-posed problems and overfitting, regularization

-   Life Sciences Engineering :

    -   *Data Sciences BsC2 2ECTS* : Statistical bases, correlation and regression, ANOVA and classification, learning principles and neural networks, kNN, well-posed problems and overfitting. Python, scikit learn